### ISSUE TITLE
Clear API documentation

### ISSUE THREAD

**Issue by Stuni907** [cursemeslowly/devrantia#1]
Nice base you did here. It sounds really interesting.

I think, if you make a clear api doc, you can easily create a mobile app. Use something like swagger.
Do you want to use Laravel? What about lumen?

Greetings,
Priestoflol

**Comment by cursemeslowly** [comment]
Hey Priest of lol 😛 

No doubt you are a priest. You read my mind. Yes I am planning to create an api so anyone can use it for any purpose. I have decided to use laravel instead of lumen because although the focus is on api calls, we still need a simple frontend to access and use the app easily while implementation.
